spring:
  output:
    ansi:
      enabled: always
  jersey:
    init:
      jersey:
        config:
          server:
            response:
              setStatusOverSendError: true
  profiles:
    active: dev
server:
  port: 4560