spring:
  data:
    mongodb:
      uri: mongodb://admin:123@cluster0-shard-00-00-vn7op.mongodb.net:27017,cluster0-shard-00-01-vn7op.mongodb.net:27017,cluster0-shard-00-02-vn7op.mongodb.net:27017/test?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true
      database: config
logging:
  level:
    #Spring
    org.springframework: ERROR
    #MongoDB
    org.mongodb.driver: ERROR