spring:
  data:
    mongodb:
      uri: mongodb://admin:1uDjtYS2Z7W7dLGE@cluster0-shard-00-00-w6ehd.mongodb.net:27017,cluster0-shard-00-01-w6ehd.mongodb.net:27017,cluster0-shard-00-02-w6ehd.mongodb.net:27017/test?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin
      database: config
logging:
  level:
    #Spring
    org.springframework: ERROR
    #MongoDB
    org.mongodb.driver: ERROR